# TCL File Generated by Component Editor 11.0
# Tue Jul 12 09:05:43 PDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | fpgaminer "fpgaminer" v1.0
# | null 2011.07.12.09:05:43
# | sha256 hasher
# | 
# | D:/altera/projects/Open-Source-FPGA-Bitcoin-Miner/src/ip/fpgaminer/fpgaminer.sv
# | 
# |    ./fpgaminer.sv syn, sim
# |    ./fpgaminer_core.v syn, sim
# |    ./sha-256-functions.v syn, sim
# |    ./sha256_transform.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module fpgaminer
# | 
set_module_property DESCRIPTION "sha256 hasher"
set_module_property NAME fpgaminer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME fpgaminer
set_module_property TOP_LEVEL_HDL_FILE fpgaminer.sv
set_module_property TOP_LEVEL_HDL_MODULE fpgaminer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME fpgaminer
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file fpgaminer.sv {SYNTHESIS SIMULATION}
add_file fpgaminer_core.v {SYNTHESIS SIMULATION}
add_file sha-256-functions.v {SYNTHESIS SIMULATION}
add_file sha256_transform.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s0
# | 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 1
set_interface_property s0 readWaitStates 0
set_interface_property s0 readWaitTime 0
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0

set_interface_property s0 ENABLED true

add_interface_port s0 address address Input 2
add_interface_port s0 write write Input 1
add_interface_port s0 byteenable byteenable Input 32
add_interface_port s0 writedata writedata Input 256
add_interface_port s0 read read Input 1
add_interface_port s0 readdata readdata Output 256
# | 
# +-----------------------------------
